### ISSUE TITLE
Project Outline: Feedback

### ISSUE THREAD

**Issue by lindskelsey** [Talapine/liftoff-assignments#1]
The project sounds great, and definitely solves an interesting problem!

However, I think the project might be too large for 8 weeks. I would suggest looking at an MVP that does not include processing payments. 

Maybe to start, users can track how much they've donated, without making direct payments? 

My concern with a project that relies on payments is that it's difficult to test "fake payments" to make sure your project is working correctly. PayPal has a Sandbox for you to replicate payments, but this might take an overwhelming amount of time to set up.

**Comment by Talapine** [comment]
I never responded to this issue! Forgive me.  I am all to happy to put the third party pay instruments in the "ice box".  I would really like to learn how to use their APIs, but I prefer having a working MVP first.  Thank you for giving the suggestion.
