### ISSUE TITLE
Project Planning: Feedback

### ISSUE THREAD

**Issue by lindskelsey** [Talapine/liftoff-assignments#2]
Wireframes- great start! I would recommend drawing your wireframes in the shape of a web browser. This will make it super clear how the pages are to be laid out, and how they work with each other.

User Stories- Looking pretty good, but I would challenge you to think about what value the user is getting from each action. Double check if you are using this format:

AS A [user]
I WANT [feature or action]
SO THAT [I get this benefit]

Your actions are clearly defined, but you need more clarity around what benefit or value the user is getting for the action.

**Comment by Talapine** [comment]
Hey Lindsey,
Thanks for the great feedback!  I am actually going to try to use the website you suggested for the wireframes; I had misplaced my mouse and found it too time-consuming with my pitiful laptop's touchpad, but I think the site will be a lot easier with a mouse.  At least I do have a vision of how my site should flow, fingers crossed.

Also I have refined my user stories; eventually I think I can catch on to this process.  Please review when you get a chance.

**Comment by lindskelsey** [comment]
Stories look much improved!

Don't get too bogged down with the wireframes. They are a tool to help you plan, if they are creating more road blocks then pen & paper is the way to go.

That said, making wireframes with either balsamiq or moqups can be a great addition to your README. You would be able to show how you started on paper, and then converted them to digital wireframes-- expanding & improving from where you started.

A well-documented README is definitely a huge plus, as employers will likely not clone/run your project. They will look at your README, and maybe look at your code. However, I would consider a nice README sprinkles & you want to make sure you have the ice cream (your project) first before you add the sprinkles.

So-- improve on your wireframes as you need to make sense of the app for yourself, but don't spend more time here than necessary!
